# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d406a5f1806d194a47c8edabbd6dd8e40a297d6b39ec8c17c208734f35b8d098ce0b801a8cea3bea18b517b4501b5f28f84e8f8a1449ebd4f340a8670da42a3

test:
  secret_key_base: 97b09eb7b6386485ced444237aa5daf5c704294dfea92f192980991a5d6255adeb438c121a005e1509021250bd9f65ea2c457cc56b3fb1bdf6b0c2a7a2fdfe93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
